#!/usr/bin/env python3
"""Generate the narration voices for Atticus's Big Day.

Uses the open Kokoro text-to-speech model (Apache 2.0) to speak every line in
voice-lines.json, then packs the clips into js/voice-data.js as base64 MP3 so
the game works offline and straight from a file:// URL.

Setup (once):
    python3 -m venv .venv && .venv/bin/pip install kokoro-onnx soundfile numpy
    curl -LO https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.onnx
    curl -LO https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin
Run:
    .venv/bin/python tools/gen_voice.py kokoro-v1.0.onnx voices-v1.0.bin

Clips are cached in tools/.voice-cache, so only new or changed lines are re-spoken.
"""
import base64
import hashlib
import json
import os
import subprocess
import sys
import tempfile

import numpy as np
import soundfile as sf

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, ".voice-cache")
OUT = os.path.join(ROOT, "js", "voice-data.js")

# voice, speed, pitch factor (Atticus is lifted a little so he sounds like a small boy)
SPEAKERS = {
    "N": ("af_heart", 0.92, 1.0),
    "A": ("af_sky", 1.0, 1.16),
    "M": ("af_bella", 0.98, 1.0),
    "D": ("am_michael", 0.98, 1.0),
}
SR = 24000


def process(samples, pitch):
    """Trim silence, level the loudness and return float32 mono at SR."""
    x = np.asarray(samples, dtype=np.float32)
    if pitch != 1.0:
        with tempfile.TemporaryDirectory() as td:
            a, b = os.path.join(td, "a.wav"), os.path.join(td, "b.wav")
            sf.write(a, x, SR)
            subprocess.run(
                ["ffmpeg", "-v", "error", "-y", "-i", a, "-af",
                 f"asetrate={int(SR * pitch)},aresample={SR},atempo={1 / pitch:.5f}", b],
                check=True)
            x, _ = sf.read(b, dtype="float32")
    env = np.abs(x)
    thr = max(1e-4, env.max() * 0.02)
    idx = np.where(env > thr)[0]
    if len(idx):
        x = x[max(0, idx[0] - int(0.03 * SR)): min(len(x), idx[-1] + int(0.12 * SR))]
    rms = np.sqrt(np.mean(x ** 2)) or 1e-6
    x = x * (0.12 / rms)
    peak = np.abs(x).max()
    if peak > 0.95:
        x = x * (0.95 / peak)
    fade = int(0.01 * SR)
    x[:fade] *= np.linspace(0, 1, fade)
    x[-fade:] *= np.linspace(1, 0, fade)
    return x


def to_mp3(x, path):
    with tempfile.TemporaryDirectory() as td:
        w = os.path.join(td, "x.wav")
        sf.write(w, x, SR)
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", w, "-ac", "1", "-ar", str(SR),
                        "-b:a", "48k", path], check=True)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    from kokoro_onnx import Kokoro
    kokoro = None
    os.makedirs(CACHE, exist_ok=True)
    with open(os.path.join(HERE, "voice-lines.json")) as fh:
        lines = json.load(fh)["lines"]
    out = {}
    for lid, who, text in lines:
        voice, speed, pitch = SPEAKERS[who]
        key = hashlib.sha1(f"{voice}|{speed}|{pitch}|{text}".encode()).hexdigest()[:16]
        mp3 = os.path.join(CACHE, f"{lid}-{key}.mp3")
        meta = mp3 + ".json"
        if not os.path.exists(mp3):
            if kokoro is None:
                kokoro = Kokoro(sys.argv[1], sys.argv[2])
            samples, sr = kokoro.create(text, voice=voice, speed=speed, lang="en-us")
            assert sr == SR
            x = process(samples, pitch)
            to_mp3(x, mp3)
            with open(meta, "w") as fh:
                json.dump({"d": round(len(x) / SR, 3)}, fh)
            print(f"spoke {lid:18s} {len(x) / SR:5.2f}s  {text}")
        with open(meta) as fh:
            dur = json.load(fh)["d"]
        with open(mp3, "rb") as fh:
            b64 = base64.b64encode(fh.read()).decode()
        out[lid] = {"s": who, "t": text, "d": dur, "a": b64}
    with open(OUT, "w") as fh:
        fh.write("/* Generated by tools/gen_voice.py from tools/voice-lines.json. Do not edit by hand. */\n")
        fh.write("window.AT_VOICE = ")
        json.dump(out, fh, separators=(",", ":"))
        fh.write(";\n")
    print(f"wrote {OUT} ({os.path.getsize(OUT) // 1024} KB, {len(out)} lines)")


if __name__ == "__main__":
    main()
