// Split the narration clips into the three files the game loads:
//
//   js/voice-index.js     window.AT_VOICE = {id: {s, t, d}}: speaker, text and seconds, no audio,
//                         and window.AT_VOICE_SCENES = {scene: [line ids]}: what each scene can say.
//                         Small (about 20 KB), loaded with the game scripts.
//   js/voice-data.js      AT.addVoiceAudio({id: base64 MP3}) for every line said in play.
//                         index.html loads it after AT.boot(), so the title screen never waits
//                         for 1.7 MB of audio.
//   js/voice-cartoons.js  the same for the lines only the cartoons use (and unused lines).
//                         Not in index.html: AT.boot() injects it in ?record mode only.
//
// The MP3 bytes are copied unchanged: nothing is re-encoded or re-synthesised.
// A line's scenes are found by scanning each scene file for line-id string literals
// ('n_hello'); lines in shared game code (js/game.js etc.) belong to every scene.
//
//   node tools/split-voice.mjs                     re-split the current js/voice-*.js files
//                                                  (run after a scene starts or stops saying a line)
//   node tools/split-voice.mjs --from clips.json   split a {id: {s, t, d, a}} map (tools/gen_voice.py does this)
//   node tools/split-voice.mjs --check             exit 1 if a re-split would change the files
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const exists = (p) => fs.existsSync(path.join(ROOT, p));
export const FILES = { index: 'js/voice-index.js', data: 'js/voice-data.js', cartoons: 'js/voice-cartoons.js' };
const LINE_ID = /'([nadmc]_[a-z0-9_]+)'/g;

/** Every clip as {id: {s, t, d, a}}, read from the split files or the older single js/voice-data.js. */
export function readClips() {
  const window = {};
  const AT = { addVoiceAudio(map) { for (const id in map) (window.AT_VOICE[id] = window.AT_VOICE[id] || {}).a = map[id]; } };
  const ctx = vm.createContext({ window, AT });
  window.AT_VOICE = {};
  for (const f of [FILES.index, FILES.data, FILES.cartoons]) if (exists(f)) vm.runInContext(read(f), ctx, { filename: f });
  return window.AT_VOICE;
}

/** Which lines each scene says, from the game scripts listed in index.html. */
export function sceneLines(known) {
  const scripts = [...read('index.html').matchAll(/<script src="([^"]+)"><\/script>/g)].map((m) => m[1]).filter((f) => !f.startsWith('js/voice-'));
  const idsIn = (f) => [...new Set([...read(f).matchAll(LINE_ID)].map((m) => m[1]).filter((id) => known.has(id)))];
  const scenes = {};
  const shared = [];
  for (const f of scripts) {
    const m = /^js\/scenes\/(\w+)\.js$/.exec(f);
    if (m) scenes[m[1]] = idsIn(f);
    else if (f !== 'js/cartoons.js') shared.push(...idsIn(f));
  }
  for (const k in scenes) scenes[k] = [...new Set([...scenes[k], ...shared])];
  return scenes;
}

/** The three files' contents for a clip map. */
export function render(clips) {
  const order = JSON.parse(read('tools/voice-lines.json')).lines.map(([id]) => id);
  const ids = [...order.filter((id) => clips[id]), ...Object.keys(clips).filter((id) => !order.includes(id))];
  const scenes = sceneLines(new Set(ids));
  const play = new Set(Object.values(scenes).flat());
  const q = JSON.stringify;
  const entries = (list, fn) => list.map((id) => `${q(id)}:${fn(id)}`).join(',\n');
  const audio = (list, what) => `AT.addVoiceAudio({\n${entries(list, (id) => q(clips[id].a))}\n}, ${q(what)});\n`;
  return {
    [FILES.index]: '/* Narration index: speaker, text and duration of every line, and the lines each scene says.\n'
      + ' * Generated by tools/split-voice.mjs (the audio is in voice-data.js and voice-cartoons.js). Do not edit by hand. */\n'
      + `window.AT_VOICE = {\n${entries(ids, (id) => q({ s: clips[id].s, t: clips[id].t, d: clips[id].d }))}\n};\n`
      + `window.AT_VOICE_SCENES = {\n${Object.keys(scenes).map((k) => `${q(k)}:${q(scenes[k])}`).join(',\n')}\n};\n`,
    [FILES.data]: '/* Narration audio for the game (base64 MP3), loaded after AT.boot().\n'
      + ' * Generated by tools/split-voice.mjs from the tools/gen_voice.py clips. Do not edit by hand. */\n'
      + audio(ids.filter((id) => play.has(id)), 'game'),
    [FILES.cartoons]: '/* Narration audio used only by the cartoons (base64 MP3), loaded in ?record mode only.\n'
      + ' * Generated by tools/split-voice.mjs from the tools/gen_voice.py clips. Do not edit by hand. */\n'
      + audio(ids.filter((id) => !play.has(id)), 'cartoons'),
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const argv = process.argv.slice(2);
  const from = argv.includes('--from') ? argv[argv.indexOf('--from') + 1] : null;
  const clips = from ? JSON.parse(fs.readFileSync(from, 'utf8')) : readClips();
  const bad = Object.keys(clips).filter((id) => !clips[id].a || !clips[id].t || !(clips[id].d > 0));
  if (bad.length) { console.error('clips without audio, text or duration:', bad.join(' ')); process.exit(1); }
  const want = new Set(JSON.parse(read('tools/voice-lines.json')).lines.map(([id]) => id));
  const missing = [...want].filter((id) => !clips[id]);
  if (missing.length) console.warn(`warning: no clip for ${missing.join(' ')} (run tools/gen_voice.py)`);
  const out = render(clips);
  if (argv.includes('--check')) {
    const stale = Object.keys(out).filter((f) => !exists(f) || read(f) !== out[f]);
    if (stale.length) { console.error(`out of date: ${stale.join(', ')} (run node tools/split-voice.mjs)`); process.exit(1); }
    console.log('voice files are up to date');
  } else {
    for (const [f, text] of Object.entries(out)) {
      fs.writeFileSync(path.join(ROOT, f), text);
      const n = (text.match(/^"[a-z]_\w+":/gm) || []).length;
      console.log(`wrote ${f} (${Math.round(text.length / 1024)} KB, ${n} lines)`);
    }
  }
}
